import { useState } from 'react';
import styles from './MetricCard.module.css';

// ── Tooltip content database ──────────────────────────────────────────────────
const TOOLTIPS = {
  'IC (Spearman)':      'Measures whether predicted rankings correlate with future returns. Positive IC means the model ranks stocks correctly. IC > 0.05 is considered good.',
  'Direction Accuracy': '% of days where the model correctly predicted up or down movement. Baseline is 50% (random). Above 52% indicates real signal.',
  'Sharpe Ratio':       'Risk-adjusted return (annualised). Higher Sharpe = better return per unit of volatility. > 1.0 is good, > 2.0 is excellent.',
  'Max Drawdown':       'Largest peak-to-trough portfolio loss during the backtest period. Smaller (less negative) is better.',
  'Strategy Return':    'Total cumulative return generated by the model\'s trading signals over the test period.',
  'Alpha vs B&H':       'Excess return over benchmark buy-and-hold. Positive alpha means the model beat simply holding the stock.',
  'Buy & Hold':         'Return from simply buying and holding the asset — the passive benchmark to beat.',
  'Alpha':              'Excess return over benchmark buy-and-hold (SPY for US stocks). Positive = model outperforms passive investing.',
  'Sortino':            'Like Sharpe but only penalises downside volatility. Higher is better. Focuses on harmful risk, not upside volatility.',
  'Rank IC':            'Information Coefficient — Spearman correlation between predicted and actual stock ranks. Higher is better.',
  'Hit Rate':           '% of periods where long stocks outperformed short stocks. Above 55% indicates consistent edge.',
  'Win/Loss Ratio':     'Average winning trade return divided by average losing trade return. > 1 means wins are larger than losses.',
  'Turnover':           'Average daily portfolio turnover. Lower turnover means fewer transactions and lower costs.',
  'Direction Acc.':     '% of predictions where the directional call (up/down) was correct.',
  'Precision@Top5':     'Of the top-5 ranked stocks predicted to outperform, what % actually did outperform the median.',
  'Long Hit Rate':      '% of long positions that had positive returns in the holding period.',
  'Short Hit Rate':     '% of short positions that had negative returns (i.e., correctly predicted to fall).',
  'Information Ratio':  'Alpha divided by tracking error. Measures consistency of excess returns vs the benchmark.',
  'Annual Return':      'Compounded annual growth rate (CAGR) of the strategy over the backtest period.',
  'Annual Volatility':  'Annualised standard deviation of daily returns. Lower means less risk.',
};

export default function MetricCard({ label, value, sub, color = 'accent', icon, delta, size = 'md', tooltip }) {
  const [showTooltip, setShowTooltip] = useState(false);

  const colorMap = {
    accent: 'var(--accent)',
    green:  'var(--green)',
    red:    'var(--red)',
    amber:  'var(--amber)',
    purple: 'var(--purple)',
  };
  const c = colorMap[color] || colorMap.accent;
  const tipText = tooltip || TOOLTIPS[label] || null;

  return (
    <div
      className={`${styles.card} ${styles[size]}`}
      style={{ '--card-color': c }}
      onMouseEnter={() => tipText && setShowTooltip(true)}
      onMouseLeave={() => setShowTooltip(false)}
    >
      <div className={styles.glow} />
      <div className={styles.scanLine} />
      {icon && <div className={styles.icon}>{icon}</div>}
      <div className={styles.label}>
        {label}
        {tipText && <span className={styles.infoIcon}>?</span>}
      </div>
      <div className={styles.value}>{value}</div>
      {sub && <div className={styles.sub}>{sub}</div>}
      {delta !== undefined && (
        <div className={`${styles.delta} ${delta >= 0 ? styles.pos : styles.neg}`}>
          {delta >= 0 ? '▲' : '▼'} {Math.abs(delta).toFixed(3)}
        </div>
      )}
      <div className={styles.corner} />

      {/* Tooltip hover card */}
      {tipText && showTooltip && (
        <div className={styles.tooltip}>
          <div className={styles.tooltipArrow} />
          <div className={styles.tooltipLabel}>{label}</div>
          <div className={styles.tooltipText}>{tipText}</div>
        </div>
      )}
    </div>
  );
}
